#%RAML 1.0 DataType
properties:
  id: number
  nome_impresso:
    type: string
  codigo_seguranca:
    description: Código de segurança do cartão
    type: string
  data_validade:
    description: Data de validade
    type: date-only
